### ISSUE TITLE
There is builtin method for almost same functionality

### ISSUE THREAD

**Issue by RayJameson** [sontungexpt/url-open#3]
Hello, I'm not trying to be mean, maybe you overlooked it, but there is `vim.ui.open` method in neovim, it basically does the same thing as this plugin.

**Comment by sontungexpt** [comment]
Hello, you're right, I don't know about vim.ui.open, I wrote this plugin because I want to learn about writing a plugin and at the same time I want to have a highlight effect when the cursor is over the url like when hovering
