### ISSUE TITLE
'localhost' domain URLs are not recognized

### ISSUE THREAD

**Issue by andis-sprinkis** [sontungexpt/url-open#6]
URLs that contain `localhost` as the domain, e.g. `https://localhost`, `https://localhost:8000/` are not being recognized by this plugin.

**Comment by sontungexpt** [comment]
> URLs that contain `localhost` as the domain, e.g. `https://localhost`, `https://localhost:8000/` are not being recognized by this plugin.

You can set `deep_pattern = true` to recognize it 
![image](https://github.com/sontungexpt/url-open/assets/92097639/ecfefed0-111b-4358-a48d-180f978ee1ba)

**Comment by andis-sprinkis** [comment]
Thanks, just found that out.

**Comment by andis-sprinkis** [comment]
Closing.
