### ISSUE TITLE
`require("url_open")` in url-open#configuration

### ISSUE THREAD

**Issue by kohane27** [sontungexpt/url-open#7]
From [configuration](https://github.com/sontungexpt/url-open#configuration):

```
require("url_open").setup({})
```

should be:

```
require("url-open").setup({})
```

Great handy plugin! Thank you!

**Comment by sontungexpt** [comment]
> From [configuration](https://github.com/sontungexpt/url-open#configuration):
> 
> ```
> require("url_open").setup({})
> ```
> 
> should be:
> 
> ```
> require("url-open").setup({})
> ```
> 
> Great handy plugin! Thank you!

Thanks for reminding me
