### ISSUE TITLE
Error with `deep_pattern = true` when scrolling binary files

### ISSUE THREAD

**Issue by andis-sprinkis** [sontungexpt/url-open#8]
Opening binary file, like PNG image or WAV audio file and scrolling forward causes this error message to pop up:

```
Error detected while processing CursorMoved Autocommands for "*":
Error executing lua callback: Vim:E976: using Blob as a String
stack traceback:
        [C]: in function 'matchstrpos'
        ...are/nvim/lazy/url-open/lua/url-open/modules/handlers.lua:106: in function 'find_first_url_in_l
ine'
        ...are/nvim/lazy/url-open/lua/url-open/modules/handlers.lua:173: in function 'foreach_url_in_line
'
        ...re/nvim/lazy/url-open/lua/url-open/modules/highlight.lua:48: in function 'highlight_cursor_url
'
        ...hare/nvim/lazy/url-open/lua/url-open/modules/autocmd.lua:35: in function <...hare/nvim/lazy/ur
l-open/lua/url-open/modules/autocmd.lua:34>

```

*Minimal* config:

```lua
local fn = vim.fn

local lazypath = fn.stdpath("data") .. "/lazy/lazy.nvim"

if not vim.loop.fs_stat(lazypath) then
  if fn.confirm("Download and initialize the configured plugins?", "&Yes\n&No", 2) == 2 then return end
  fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath })
end

vim.opt.rtp:prepend(lazypath)

require("lazy").setup(
  {
    'sontungexpt/url-open',
    config = function()
      require("url-open").setup({
        deep_pattern = true,
      })
    end,
  }
)
```

`nvim --version`:

```
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1697887905

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by sontungexpt** [comment]
> Opening binary file, like PNG image or WAV audio file and scrolling forward causes this error message to pop up:
> 
> ```
> Error detected while processing CursorMoved Autocommands for "*":
> Error executing lua callback: Vim:E976: using Blob as a String
> stack traceback:
>         [C]: in function 'matchstrpos'
>         ...are/nvim/lazy/url-open/lua/url-open/modules/handlers.lua:106: in function 'find_first_url_in_l
> ine'
>         ...are/nvim/lazy/url-open/lua/url-open/modules/handlers.lua:173: in function 'foreach_url_in_line
> '
>         ...re/nvim/lazy/url-open/lua/url-open/modules/highlight.lua:48: in function 'highlight_cursor_url
> '
>         ...hare/nvim/lazy/url-open/lua/url-open/modules/autocmd.lua:35: in function <...hare/nvim/lazy/ur
> l-open/lua/url-open/modules/autocmd.lua:34>
> ```
> 
> _Minimal_ config:
> 
> ```lua
> local fn = vim.fn
> 
> local lazypath = fn.stdpath("data") .. "/lazy/lazy.nvim"
> 
> if not vim.loop.fs_stat(lazypath) then
>   if fn.confirm("Download and initialize the configured plugins?", "&Yes\n&No", 2) == 2 then return end
>   fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath })
> end
> 
> vim.opt.rtp:prepend(lazypath)
> 
> require("lazy").setup(
>   {
>     'sontungexpt/url-open',
>     config = function()
>       require("url-open").setup({
>         deep_pattern = true,
>       })
>     end,
>   }
> )
> ```
> 
> `nvim --version`:
> 
> ```
> NVIM v0.9.4
> Build type: Release
> LuaJIT 2.1.1697887905
> 
>    system vimrc file: "$VIM/sysinit.vim"
>   fall-back for $VIM: "/usr/share/nvim"
> 
> Run :checkhealth for more info
> ```

Thanks for your reporting.

**Comment by sontungexpt** [comment]
> Opening binary file, like PNG image or WAV audio file and scrolling forward causes this error message to pop up:
> 
> ```
> Error detected while processing CursorMoved Autocommands for "*":
> Error executing lua callback: Vim:E976: using Blob as a String
> stack traceback:
>         [C]: in function 'matchstrpos'
>         ...are/nvim/lazy/url-open/lua/url-open/modules/handlers.lua:106: in function 'find_first_url_in_l
> ine'
>         ...are/nvim/lazy/url-open/lua/url-open/modules/handlers.lua:173: in function 'foreach_url_in_line
> '
>         ...re/nvim/lazy/url-open/lua/url-open/modules/highlight.lua:48: in function 'highlight_cursor_url
> '
>         ...hare/nvim/lazy/url-open/lua/url-open/modules/autocmd.lua:35: in function <...hare/nvim/lazy/ur
> l-open/lua/url-open/modules/autocmd.lua:34>
> ```
> 
> _Minimal_ config:
> 
> ```lua
> local fn = vim.fn
> 
> local lazypath = fn.stdpath("data") .. "/lazy/lazy.nvim"
> 
> if not vim.loop.fs_stat(lazypath) then
>   if fn.confirm("Download and initialize the configured plugins?", "&Yes\n&No", 2) == 2 then return end
>   fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath })
> end
> 
> vim.opt.rtp:prepend(lazypath)
> 
> require("lazy").setup(
>   {
>     'sontungexpt/url-open',
>     config = function()
>       require("url-open").setup({
>         deep_pattern = true,
>       })
>     end,
>   }
> )
> ```
> 
> `nvim --version`:
> 
> ```
> NVIM v0.9.4
> Build type: Release
> LuaJIT 2.1.1697887905
> 
>    system vimrc file: "$VIM/sysinit.vim"
>   fall-back for $VIM: "/usr/share/nvim"
> 
> Run :checkhealth for more info
> ```

Fixed
